name: CI/CD

# Event Trigger
on:
  push:
    branches:
      - main
      - develop
      - feature/librarization

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test

      ## Gradle Caching
#      - name: Gradle Caching
#        uses: actions/cache@v3
#        with:
#          path: |
#            - /.gradle/caches
#            - /.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#            restore-keys: |
#              ${{ runner.os }}-gradle-
